# Generated by Django 3.1.5 on 2021-01-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reinosdeferro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('publicado', 'Publicado'), ('rascunho', 'Rascunho')], default='rascunho', max_length=10),
        ),
    ]
